server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

pg:
  base-url: http://localhost:8082
  callback-url: http://localhost:8080/api/v1/payments/callback
  connect-timeout-ms: 2000
  read-timeout-ms: 3000
  # 운영 환경별 오버라이드는 아래 profile 섹션에서 설정

kafka:
  topics:
    catalog-events: catalog-events-v1
    order-events: order-events-v1
  outbox:
    poll-interval-ms: 3000
    batch-size: 100

resilience4j:
  circuitbreaker:
    instances:
      pgCircuit:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
  retry:
    instances:
      pgRetry:
        max-attempts: 2
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
        fail-after-max-attempts: true

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

pg:
  base-url: ${PG_BASE_URL:http://pg-simulator:8082}
  callback-url: ${PG_CALLBACK_URL:http://commerce-api:8080/api/v1/payments/callback}

---
spring:
  config:
    activate:
      on-profile: qa

pg:
  base-url: ${PG_BASE_URL:http://pg-simulator:8082}
  callback-url: ${PG_CALLBACK_URL:http://commerce-api:8080/api/v1/payments/callback}

---
spring:
  config:
    activate:
      on-profile: prd

pg:
  base-url: ${PG_BASE_URL}
  callback-url: ${PG_CALLBACK_URL}

springdoc:
  api-docs:
    enabled: false